In [29]:
# torch no grad test
import torch

a = torch.rand((3, 5), requires_grad=True)
out = a* 2 + 1
print(a)
print(out)
out.sum().backward()

tensor([[0.9209, 0.2911, 0.5884, 0.4174, 0.6902],
        [0.2626, 0.7401, 0.3204, 0.0387, 0.1321],
        [0.0774, 0.7245, 0.7116, 0.3854, 0.7554]], requires_grad=True)
tensor([[2.8417, 1.5821, 2.1768, 1.8349, 2.3804],
        [1.5252, 2.4802, 1.6408, 1.0774, 1.2642],
        [1.1548, 2.4489, 2.4232, 1.7708, 2.5108]], grad_fn=<AddBackward0>)


In [30]:
print(a.grad)

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])


In [38]:
import torch

a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
print(a, b,end='\n')

tensor([2., 3.], requires_grad=True) tensor([6., 4.], requires_grad=True)


In [40]:
with torch.no_grad():
    #Q = 3*a**3 - b**2
    pass
H = 3*a**3 - b**2
Q = 3*a**3 - b**2    

In [45]:
external_grad = torch.tensor([1., 1.])
L = Q  + H
L.backward(gradient=external_grad)

RuntimeError: Trying to backward through the graph a second time (or directly access saved variables after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved variables after calling backward.

In [44]:
print(a.grad)
print(b.grad)

tensor([ 72., 162.])
tensor([-24., -16.])
